#ifndef PASSY_OID_NIDS_H
#define PASSY_OID_NIDS_H

/* DO NOT MODIFY THIS FILE
 * This file was generated by gen_oid_nid_list.py
 */

#include <OBJECT_IDENTIFIER.h>

typedef struct OID_NID_s {
    OBJECT_IDENTIFIER_t oid;
    int nid;
} OID_NID_t;

#define NUM_NID 30

#define NID_undef                             0
#define NID_member_body                       1
#define NID_identified_organization           2
#define NID_etsi                              3
#define NID_etsi_identified_organization      4
#define NID_bsi_de                            5
#define NID_id_PACE                           6
#define NID_id_PACE_DH_GM                     7
#define NID_id_PACE_DH_GM_3DES_CBC_CBC        8
#define NID_id_PACE_DH_GM_AES_CBC_CMAC_128    9
#define NID_id_PACE_DH_GM_AES_CBC_CMAC_192    10
#define NID_id_PACE_DH_GM_AES_CBC_CMAC_256    11
#define NID_id_PACE_ECDH_GM                   12
#define NID_id_PACE_ECDH_GM_3DES_CBC_CBC      13
#define NID_id_PACE_ECDH_GM_AES_CBC_CMAC_128  14
#define NID_id_PACE_ECDH_GM_AES_CBC_CMAC_192  15
#define NID_id_PACE_ECDH_GM_AES_CBC_CMAC_256  16
#define NID_id_PACE_DH_IM                     17
#define NID_id_PACE_DH_IM_3DES_CBC_CBC        18
#define NID_id_PACE_DH_IM_AES_CBC_CMAC_128    19
#define NID_id_PACE_DH_IM_AES_CBC_CMAC_192    20
#define NID_id_PACE_DH_IM_AES_CBC_CMAC_256    21
#define NID_id_PACE_ECDH_IM                   22
#define NID_id_PACE_ECDH_IM_3DES_CBC_CBC      23
#define NID_id_PACE_ECDH_IM_AES_CBC_CMAC_128  24
#define NID_id_PACE_ECDH_IM_AES_CBC_CMAC_192  25
#define NID_id_PACE_ECDH_IM_AES_CBC_CMAC_256  26
#define NID_id_PACE_ECDH_CAM                  27
#define NID_id_PACE_ECDH_CAM_AES_CBC_CMAC_128 28
#define NID_id_PACE_ECDH_CAM_AES_CBC_CMAC_192 29
#define NID_id_PACE_ECDH_CAM_AES_CBC_CMAC_256 30

#endif
