/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_SecurityInfos_H_
#define	_SecurityInfos_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SecurityInfo;

/* SecurityInfos */
typedef struct SecurityInfos {
	A_SET_OF(struct SecurityInfo) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityInfos_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityInfos;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SecurityInfo.h"

#endif	/* _SecurityInfos_H_ */
#include <asn_internal.h>
