/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#ifndef	_SecurityInfo_H_
#define	_SecurityInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SecurityInfo */
typedef struct SecurityInfo {
	OBJECT_IDENTIFIER_t	 protocol;
	ANY_t	 requiredData;
	ANY_t	*optionalData	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_SecurityInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_SecurityInfo_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityInfo_H_ */
#include <asn_internal.h>
