/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Passport"
 * 	found in "eMRTD.asn1"
 * 	`asn1c -D ./lib/asn1 -no-gen-example -pdu=all`
 */

#include "SecurityInfo.h"

asn_TYPE_member_t asn_MBR_SecurityInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SecurityInfo, protocol),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"protocol"
		},
	{ ATF_ANY_TYPE | ATF_NOFLAGS, 0, offsetof(struct SecurityInfo, requiredData),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"requiredData"
		},
	{ ATF_ANY_TYPE | ATF_POINTER, 1, offsetof(struct SecurityInfo, optionalData),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"optionalData"
		},
};
static const int asn_MAP_SecurityInfo_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_SecurityInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SecurityInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* protocol */
};
asn_SEQUENCE_specifics_t asn_SPC_SecurityInfo_specs_1 = {
	sizeof(struct SecurityInfo),
	offsetof(struct SecurityInfo, _asn_ctx),
	asn_MAP_SecurityInfo_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_SecurityInfo_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SecurityInfo = {
	"SecurityInfo",
	"SecurityInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_SecurityInfo_tags_1,
	sizeof(asn_DEF_SecurityInfo_tags_1)
		/sizeof(asn_DEF_SecurityInfo_tags_1[0]), /* 1 */
	asn_DEF_SecurityInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_SecurityInfo_tags_1)
		/sizeof(asn_DEF_SecurityInfo_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SecurityInfo_1,
	3,	/* Elements count */
	&asn_SPC_SecurityInfo_specs_1	/* Additional specs */
};

